### ISSUE TITLE
Add biolink categories to monarch.owl

### ISSUE THREAD

**Issue by kshefchek** [TranslatorSRI/reference-kg#1]
test out using https://github.com/monarch-initiative/dipper/blob/master/scripts/categories/Makefile#L89, although the ttl is slightly stale until https://github.com/biolink/biolinkml/issues/193 is fixed

**Comment by kshefchek** [comment]
@deepakunni3 what output format is best (obo json, ntriples, tsv?)

**Comment by matentzn** [comment]
We should coordinate this maybe with the monarch-ontology export.. This framework I build does basic biolink typing as well.

**Comment by kshefchek** [comment]
we will use https://archive.monarchinitiative.org/202009/rdf/blcategories/class-category.ttl
