### ISSUE TITLE
Move to ITRB

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/reference-kg#16]
![image](https://user-images.githubusercontent.com/10744350/183923120-31ceb396-a8b9-4f63-bf5d-18ceca1e684b.png)

* Deploy to ITRB production asap
* We will soon want ITRB staging and testing
* dev can point at the local instance.

If we need a stopgap, it's possible that @YaphetKG could fold this into the automat deployment onto ITRB since it's a plater-based KP?

**Comment by putmantime** [comment]
Kevin is working with Yaphet on this now.

**Comment by putmantime** [comment]
done and deployed at http://automat.ci.transltr.io/sri-reference-kg/
