### ISSUE TITLE
ingest of monarch.owl into kgx

### ISSUE THREAD

**Issue by kshefchek** [TranslatorSRI/reference-kg#3]
options:

- robot -> obo json
- kg-covid process created by @matentzn, https://github.com/obophenotype/covid-kg-ontology-preprocessing
- monarch-merged.owl from https://archive.monarchinitiative.org/202008/owl/monarch-merged.owl

**Comment by deepakunni3** [comment]
@matentzn The goal here is to convert monarch.owl to an OBO Graph JSON format.
But we would want to do some sensible robot operations on the owl like converting owl:equivalentClass to owl:subClassOf via robot relax

Curious to hear your thoughts on this :)
