### ISSUE TITLE
QC KGX output from monarch rdf

### ISSUE THREAD

**Issue by kshefchek** [TranslatorSRI/reference-kg#5]
Review of the output from the monarch n-triple to tsv pipeline from KGX

**Comment by TomConlin** [comment]
Noting that I  have made passes on two candidates to date; 
when a new, viable, candidate appears I will process it 
& (publicly) report as there won't be time for another round of adjustments.

**Comment by TomConlin** [comment]
[kgx_sanity_check_202009.txt](https://github.com/TranslatorSRI/reference-kg/files/5244313/kgx_sanity_check_202009.txt)
